sudo: false
language: node_js
node_js:
  - 6
  - 7
  env:
    - NODE_LOW_V=1
  - 8
  - stable

cache:
  bundle: true
  directories:
    - node_modules

before_install:
  - "npm install -g npm@latest"

install:
  - npm ci
  - lerna bootstrap

jobs:
  include:
    - stage: Document deploy
      allow_failure: true
      script: lerna run dist:demo --scope=meas-ui -- -- --output-public-path=measure
      deploy:
        edge:
          branch: v1.8.47
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
        local_dir: packages/meas-ui/demo-dist

    - stage: Test
      before_script: npm install codecov
      script: npm test -- --coverage
      after_script: codecov --token=$CODECOV_TOKEN
